language: php

php:
  - 5.6

sudo: false

install: travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-clover clover.xml
  - vendor/bin/test-reporter --coverage-report clover.xml
