# This will stand up a dev environment, see CONTRIBUTING.md for details
web:
  image: symplicity/develop
  ports:
    - "80:80"
    - "3000:3000"
    - "2222:22"
    - "443:443"
  volumes:
    - .:/var/www
  environment:
    - APP_ROOT=/var/www
  links:
    - db
### Uncomment this once jobs are ready
#job:
#  image: symplicity/job
#  volumes:
#    - .:/var/www
#  links:
#    - db
db:
  image: mariadb
  environment:
   - MYSQL_DATABASE=antidote
   - MYSQL_USER=antidote
   - MYSQL_PASSWORD=antidoteSecret
   - MYSQL_ROOT_PASSWORD=rootSecret
   - TERM=dumb
