# This will stand up a dev environment, see CONTRIBUTING.md for details
web:
  image: symplicity/develop
  ports:
    - "80:80"
    - "3000:3000"
    - "2222:22"
    - "443:443"
  volumes:
    - .:/var/www
  environment:
    - APP_ROOT=/var/www
  links:
    - db

job:
  image: symplicity/worker
  volumes:
    - .:/var/www
  links:
    - db

db:
  image: mariadb
  ports:
    - "3306:3306"
  environment:
   - MYSQL_DATABASE=antidote
   - MYSQL_USER=antidote
   - MYSQL_PASSWORD=antidoteSecret
   - MYSQL_ROOT_PASSWORD=rootSecret
   - TERM=dumb
