# This will stand up a production environment, see Deployment.md for details
# This file is required to use docker machine and docker swarm for deployment.
web:
  image: symplicity/webserver
  ports:
    - '80:80'
    - '443:443'
  environment:
    - ANTIDOTE_API_KEY=
    - ANTIDOTE_CACHE_DRIVER=memcached
    - ANTIDOTE_DB_HOST=db
    - ANTIDOTE_DB_NAME=antidote
    - ANTIDOTE_DB_PASS=antidoteSecret # Change Me
    - ANTIDOTE_DB_PORT=3306
    - ANTIDOTE_DB_USER=antidote # Change Me
    - ANTIDOTE_ROLE=web
    - CODESHIP_PROJECT_ID=
    - FDA_TOKEN=
    - GITREPO_BRANCH=production
    - 'GITREPO_URL=git@github.com:Symplicity/antidote.git'
    - MAILGUN_DOMAIN=
    - MAILGUN_PASSWORD=
    - MAILGUN_SECRET=
    - MAILGUN_USERNAME=
    - MEMCACHED_HOST=memc
    - RABBITMQ_NAME=hello
    - RABBITMQ_NODE=rabbitmq
    - RABBITMQ_PORT=5672
    - WEBHOOK_API_KEY=
    - WORKER_API_KEY=
  links:
    - db
    - rabbitmq
job:
  image: symplicity/worker
  environment:
    - ANTIDOTE_API_KEY=
    - ANTIDOTE_DB_HOST=db
    - ANTIDOTE_DB_NAME=antidote
    - ANTIDOTE_DB_PASS=antidoteSecret # Change Me
    - ANTIDOTE_DB_PORT=3306
    - ANTIDOTE_DB_USER=antidote # Change Me
    - ANTIDOTE_ROLE=worker
    - FDA_TOKEN=
    - GITREPO_BRANCH=production
    - 'GITREPO_URL=git@github.com:Symplicity/antidote.git'
    - MAILGUN_DOMAIN=
    - MAILGUN_PASSWORD=
    - MAILGUN_SECRET=
    - MAILGUN_USERNAME=
    - RABBITMQ_NAME=hello
    - RABBITMQ_NODE=rabbitmq
    - RABBITMQ_PORT=5672
    - SLACK_TOKEN=
    - WEBHOOK_API_KEY=
    - WORKER_API_KEY=
  links:
    - db
    - rabbitmq
db:
  image: mariadb
  ports:
    - "3306:3306"
  environment:
   - MYSQL_DATABASE=antidote
   - MYSQL_USER=antidote # Change Me
   - MYSQL_PASSWORD=antidoteSecret # Change Me
   - MYSQL_ROOT_PASSWORD=rootSecret # Change Me
   - TERM=dumb
rabbitmq:
  image: rabbitmq:3-management
  environment:
    - RABBITMQ_NODENAME=jobs
