# Group Drugs
With the drugs API you can retrieve information and reviews on individual drugs as well as list all drugs.

## Drugs [/drugs]

+ Model

    + Headers

            Content-Type: application/json

    + Body

            {
                "total": 150,
                "per_page": 15,
                "current_page": 2,
                "last_page": 10,
                "next_page_url": "https://antidote.symplicity-opensource.com/api/drugs?page=3",
                "prev_page_url": "https://antidote.symplicity-opensource.com/api/drugs?page=1",
                "from": 16,
                "to": 30,
                "data": [
                    {
                        "id": 1,
                        "label": "Tylenol",
                        "description": "Tylenol is used to treat pain.",
                        "generic": "Acetaminophen",
                        "drug_forms": [
                            "Disintegrating Oral Tablet",
                            "Oral Capsule"
                        ],
                        "generic_id": null,
                        "prescription_type": "OTC",
                        "recalls": [],
                        "effectiveness_percentage": 0,
                        "insurance_coverage_percentage": 0,
                        "total_reviews": 0,
                        "side_effects": [
                            {
                                "id": "1",
                                "value": "fatigue"
                            },
                            {
                                "id": "2",
                                "value": "weight-loss"
                            },
                            {
                                "id": "3",
                                "value": "reduced visual acuity"
                            }
                        ]
                    },
                    {
                        "id": 2,
                        "label": "Claritin",
                        "description": "Claritin is used to treat allergies",
                        "generic": null,
                        "drug_forms": [
                            "Disintegrating Oral Tablet",
                            "Oral Capsule"
                        ],
                        "generic_id": null,
                        "prescription_type": "Prescription and OTC",
                        "recalls": [],
                        "effectiveness_percentage": 0.75,
                        "insurance_coverage_percentage": 0.25,
                        "total_reviews": 50,
                        "side_effects": [
                            {
                                "id": "3",
                                "value": "reduced visual acuity"
                            },
                            {
                                "id": "4",
                                "value": "blurred vision"
                            },
                            {
                                "id": "5",
                                "value": "varicose vein"
                            }
                        ]
                    }
                ]
            }

### List [GET /drugs{?keywords,page,limit}]
Returns a list of all drugs. The drugs are returned in alphabetically sorted order. Example:

```no-highlight
https://antidote.symplicity-opensource.com/api/drugs?keywords=Tylenol
```

+ Parameters

    + keywords: `Tylenol` (string, optional) - Search for a drug by keywords in label or description
    + page: `1` (integer, optional) - Page number of drugs
    + limit: `25` (integer, optional) - The maximum number of drugs to return, up to `500`
      + Default: `15`

+ Response 200

    [Drugs][]

## Drug [/drugs/{id}]

+ Parameters

    + id: `1` (required, integer) - The drug ID

+ Model

    + Headers

            Content-Type: application/json

    + Body

            {
                "id": 1,
                "label": "Tylenol",
                "description": "Tylenol is used to treat pain.",
                "drug_forms": [
                    "Disintegrating Oral Tablet",
                    "Oral Capsule"
                ],
                "side_effects": [
                    {
                        "id": 1,
                        "value": "Nausea"
                    },
                    {
                        "id": 2,
                        "value": "Diarrhea"
                    }
                ],
                "generic_id": 45,
                "indications": [
                    {
                        "id": "1",
                        "value": "pulmonary arterial hypertension"
                    },
                    {
                        "id": "2",
                        "value": "plasma cell myeloma"
                    }
                ],
                "prescription_type": "OTC",
                "recalls": [
                    {
                        "number": "91201096",
                        "date": "19880508",
                        "recall": "Quidem iure eaque eveniet placeat odit architecto. Et pariatur cum ea hic consequatur iste quia. Sed voluptates aliquid voluptate saepe quae optio. Aut voluptas quia rerum. Quia unde vel hic quasi assumenda officia.",
                        "lots": "Lot Number: 54014927, Exp 06 / 28 / 1983"
                    }
                ],
                "effectiveness_percentage": 0.18,
                "insurance_coverage_percentage": 0.64,
                "total_reviews": 11
            }

### Get Drug [GET]

+ Response 200

    [Drug][]

## Drug Review [/drugs/{id}/reviews]
+ Parameters
    + id: `1` (required, integer) - The drug ID

+ Model

    + Headers

            Content-Type: application/json

    + Body

            {
                "total": 45,
                "per_page": 15,
                "current_page": 2,
                "last_page": 1,
                "next_page_url": "https://antidote.symplicity-opensource.com/api/drugs/5/reviews?page=3",
                "prev_page_url": "https://antidote.symplicity-opensource.com/api/drugs/5/reviews?page=1",
                "from": 16,
                "to": 30,
                "data": [
                    {
                        "id": 1514,
                        "rating": 3,
                        "is_covered_by_insurance": 1,
                        "comment": "Tylenol hurt my liver a lot",
                        "created_at": "2015-06-23 02:57:19",
                        "upvotes": 24,
                        "downvotes": 26,
                        "user": {
                            "id": 3,
                            "username": "dedric",
                            "created_at": "2015-06-22 18:49:02",
                            "updated_at": "2015-06-22 18:49:02",
                            "age": 23,
                            "gender": "m"
                        },
                        "drug": {
                            "id": 5,
                            "label": "Tylenol",
                            "description": "Tylenol is a medicine used to treat pain."
                        },
                        "side_effects": [
                            {
                                "id": 1,
                                "value": "nausea"
                            },
                            {
                                "id": 2,
                                "value": "diarrhea"
                            }
                        ]
                    },
                    {
                        "id": 1514,
                        "rating": 3,
                        "is_covered_by_insurance": 1,
                        "comment": "Makes you sleepy",
                        "created_at": "2015-06-23 02:57:19",
                        "upvotes": 400,
                        "downvotes": 100,
                        "user": {
                            "id": 3,
                            "username": "dedric",
                            "created_at": "2015-06-22 18:49:02",
                            "updated_at": "2015-06-22 18:49:02",
                            "age": 23,
                            "gender": "m"
                        },
                        "drug": {
                            "id": 5,
                            "label": "Claritin",
                            "description": "Claritin is used to treat allergies."
                        },
                        "side_effects": [
                            {
                                "id": 1,
                                "value": "Nausea"
                            }
                        ]
                    }
                ]
            }

### List All [GET /drugs/{id}/reviews{?keywords,page,limit}]
Returns a list of all reviews for a drug. The reviews are returned in created date descending order.  Example:

```no-highlight
https://antidote.symplicity-opensource.com/api/drugs/1/reviews
```

+ Parameters

    + id: `1` (required, integer) - The drug ID
    + keywords: `pain` (string, optional) - Search for a drug review by keywords in the comment
    + page: `1` (integer, optional) - Page number
    + limit: `25` (integer, optional) - The maximum number of drug reviews to return, up to `500`
      + Default: `15`

+ Response 200

    [Drug Review][]

### Create New [POST /drugs/{id}/reviews]
Create a new drug review using this action. It takes a JSON object containing the following fields:

    - rating: `3` (required, integer) - The rating the user gave the drug either 1, 2, 3 - 3 is best
    - is_covered_by_insurance: `1` (integer, required) - Was the drug covered by insurance?
    - comment: `My pain has subsided considerably since I started taking this.` (text, optional) - User comments
    - side_effects: `[1,2,3]` (array, optional) - Side effects experienced by the user

+ Authentication: bearer

+ Parameters
    + id: `1` (required, integer) - The drug ID

+ Request
    + Headers

            Content-Type: application/json

    + Body

            {
                "rating": "3",
                "is_covered_by_insurance": "1",
                "comment": "My pain has subsided considerably since I started taking this.",
                "side_effects": [1,2,3]
            }

+ Response 201
    + Headers

            Content-Type: application/json

    + Body

            {
                "age": 82,
                "rating": "3",
                "comment": "My pain has subsided considerably since I started taking this.",
                "is_covered_by_insurance": "1",
                "created_at": "2015-06-29 16:01:00",
                "id": 503,
                "upvotes": 0,
                "downvotes": 0
            }

+ Response 400
    + Headers

            Content-Type: application/json

    + Body

            {
              "message": {
                "rating": [
                  "The rating field is required."
                ]
              }
            }

## Drug Alternative [/drugs/{id}/alternatives]

### List All [GET /drugs/{id}/alternatives{?page,limit}]
Returns a list of all alternative drugs for a drug. The drugs are returned in alphabetically sorted order.  Example:

```no-highlight
https://antidote.symplicity-opensource.com/api/drugs/1/alternatives
```

+ Parameters

    + id: `1` (required, integer) - The drug ID
    + page: `2` (integer, optional) - Page number
    + limit: `25` (integer, optional) - The maximum number of drug alternatives to return, up to `50`
      + Default: `15`

+ Response 200

    [Drugs][]

## Voting [/drug-reviews/{id}/vote]

### Create New [POST /drug-reviews/{id}/vote]
Vote on a drug review using this action. It takes a JSON object containing the following field:

    - vote: `1` (required, integer) - The user's vote - either 1 for upvote, or -1 for downvote

+ Authentication: bearer

+ Parameters
    + id: `1` (required, integer) - The drug review ID

+ Request
    + Headers

            Content-Type: application/json

    + Body

            {
                "vote": "1"
            }

+ Response 201
    + Headers

            Content-Type: application/json

    + Body

            {
                "id": "2",
                "user_id": "1",
                "drug_review_id": "1",
                "vote": 1,
                "created_at": "2015-06-29 14:51:47",
                "updated_at": "2015-06-29 14:51:47"
            }

+ Response 400

    + Body

            {
              "message": {
                "rating": [
                  "The vote field is required."
                ]
              }
            }

## Autocomplete [/autocomplete/drugs]
You can use the autocomplete API on various resources to get an optimized list of id and value pairs.

## Drugs [GET /autocomplete/drugs{?term,limit,include_generics}]
Returns a list of drugs. The drugs are returned in alphabetically sorted order. Example:

```no-highlight
https://antidote.symplicity-opensource.com/api/autocomplete/drugs?term=Tyl
```

+ Parameters

    + term: `Tyl` (string, optional) - Search for a drug by label
    + include_generics: `1` (integer, optional) - Include generic label in search
    + limit: `25` (integer, optional) - The maximum number of drugs to return, up to `500`
      + Default: `15`

+ Response 200

        [
            {
                "id": "3",
                "label": "Tylenol",
                "generic": "Acetaminophen"
            },
            {
                "id": "16",
                "label": "Tylenol III",
                "generic": "Codeine"
            }
        ]
